[package]
name = "fe-test-runner"
version = "0.26.0"
authors = ["The Fe Developers <snakecharmers@ethereum.org>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/ethereum/fe"

[dependencies]
hex="0.4"
bytes = "1.3"
colored = "2.0"
ethabi = { default-features = false, features = ["full-serde"], version = "18.0" }
indexmap = "1.6.2"

# used by revm; we need to force the js feature for wasm support
getrandom = { version = "0.2.8", features = ["js"] }
revm = { version = "8.0", default-features = false }
